#!/usr/bin/env bash
# classify-task-fingerprint.sh — Deterministic task -> read-bundle routing.
#
#   classify-task-fingerprint.sh "<task description>" [--json]
#       Recommend the smallest useful READ_BUNDLES.md bundle for the task so an
#       agent loads the right context instead of guessing. On no match or a tie
#       it returns 'ambiguous' and tells the agent to clarify before broad edits.
#   classify-task-fingerprint.sh --write | --check
#       Regenerate / verify _system/TASK_FINGERPRINT_ROUTING.md from the routing
#       table, and verify every bundle name exists as a heading in READ_BUNDLES.md.
set -euo pipefail
SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/aiaast-lib.sh
source "${SCRIPT_DIR}/lib/aiaast-lib.sh"
TEMPLATE_ROOT="$(cd -- "${SCRIPT_DIR}/.." && pwd)"

routing="${TEMPLATE_ROOT}/_system/task-fingerprint-routing.json"
bundles_doc="${TEMPLATE_ROOT}/_system/READ_BUNDLES.md"
doc_out="${TEMPLATE_ROOT}/_system/TASK_FINGERPRINT_ROUTING.md"

MODE="classify"; JSON=0; TASK=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --write) MODE="write"; shift ;;
    --check) MODE="check"; shift ;;
    --json) JSON=1; shift ;;
    -h|--help) sed -n '2,12p' "$0"; exit 0 ;;
    *) TASK="${TASK:+${TASK} }$1"; shift ;;
  esac
done
aiaast_require_file "${routing}" || { echo "task_fingerprint_failed missing=${routing}"; exit 1; }

if [[ "${MODE}" != "classify" ]]; then
  tmp="$(mktemp)"; err="$(mktemp)"; trap 'rm -f "${tmp}" "${err}"' EXIT
  if ! python3 - "${routing}" "${bundles_doc}" "${tmp}" >"${err}" 2>&1 <<'PY'
import json, sys
from pathlib import Path
routing = json.loads(Path(sys.argv[1]).read_text())
doc = Path(sys.argv[2]).read_text() if Path(sys.argv[2]).exists() else ""
out = sys.argv[3]
errors, lines = [], []
lines.append("# Task Fingerprint Routing")
lines.append("")
lines.append("> GENERATED by `bootstrap/classify-task-fingerprint.sh` from")
lines.append("> `_system/task-fingerprint-routing.json`. Do not edit by hand. Run")
lines.append("> `classify-task-fingerprint.sh \"<your task>\"` to get a routing.")
lines.append("")
lines.append("| If the task mentions… | Load this bundle | Also |")
lines.append("|---|---|---|")
for r in routing["routes"]:
    if r["bundle"] not in doc:
        errors.append(f"route '{r['id']}': bundle '{r['bundle']}' not found as a heading in READ_BUNDLES.md")
    sample = ", ".join(p.replace("\\\\b", "").replace("\\\\", "") for p in r["patterns"][:3])
    lines.append(f"| {sample} | **{r['bundle']}** | {r.get('also','')} |")
lines.append("")
lines.append("On no match or a tie the classifier returns `task_fingerprint_ambiguous` —")
lines.append("clarify the task before making broad edits.")
if errors:
    for e in errors: print(e)
    sys.exit(1)
Path(out).write_text("\n".join(lines).rstrip() + "\n")
PY
  then
    echo "task_fingerprint_routing_failed"; cat "${err}"; exit 1
  fi
  if [[ "${MODE}" == "check" ]]; then
    if [[ ! -f "${doc_out}" ]] || ! diff -q "${tmp}" "${doc_out}" >/dev/null 2>&1; then
      echo "task_fingerprint_routing_stale: regenerate with classify-task-fingerprint.sh --write"; exit 1
    fi
    echo "task_fingerprint_routing_current path=_system/TASK_FINGERPRINT_ROUTING.md"; exit 0
  fi
  cp "${tmp}" "${doc_out}"; echo "Wrote ${doc_out}"; exit 0
fi

[[ -z "${TASK}" ]] && { echo "usage: $0 \"<task description>\" [--json]"; exit 2; }

result="$(python3 - "${routing}" "${TASK}" <<'PY'
import json, re, sys
routing = json.loads(open(sys.argv[1]).read())
task = sys.argv[2].lower()
scores = []
for r in routing["routes"]:
    n = sum(1 for p in r["patterns"] if re.search(p, task, re.I))
    if n:
        scores.append((n, r["id"], r["bundle"], r.get("also", "")))
scores.sort(reverse=True)
if not scores:
    print(json.dumps({"result": "task_fingerprint_ambiguous", "reason": "no signal matched", "bundle": None}))
elif len(scores) > 1 and scores[0][0] == scores[1][0]:
    tied = [s[2] for s in scores if s[0] == scores[0][0]]
    print(json.dumps({"result": "task_fingerprint_ambiguous", "reason": "multiple bundles tied", "candidates": tied}))
else:
    top = scores[0]
    print(json.dumps({"result": "task_fingerprint_ok", "route": top[1], "bundle": top[2], "also": top[3], "score": top[0]}))
PY
)"

if [[ ${JSON} -eq 1 ]]; then
  aiaast_json_ok "${result}" "classify-task-fingerprint.sh" "routing"
else
  printf '%s\n' "${result}"
fi
