#!/usr/bin/env bash
# generate-system-nervous-system.sh — Generate the System Nervous System map.
#
# One-page operational control map: every MAJOR subsystem -> owner file, validator,
# downstream impact, failure mode, recovery command. Curated semantics live in
# _system/subsystem-definitions.json; factual fields (owner authority + downstream
# policy) are joined from the enriched _system/SYSTEM_REGISTRY.json so the map cannot
# silently drift. This compresses CONTEXT_INDEX.md into routing, not a file index.
#
#   generate-system-nervous-system.sh [target] [--write|--check]
set -euo pipefail
SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/aiaast-lib.sh
source "${SCRIPT_DIR}/lib/aiaast-lib.sh"

usage() { echo "usage: $0 [target-repo] [--write|--check]"; }

TARGET=""; MODE="print"
while [[ $# -gt 0 ]]; do
  case "$1" in
    --write) MODE="write"; shift ;;
    --check) MODE="check"; shift ;;
    -h|--help) usage; exit 0 ;;
    *) [[ -z "${TARGET}" ]] && { TARGET="$1"; shift; } || { echo "unexpected: $1" >&2; exit 2; } ;;
  esac
done
[[ -z "${TARGET}" ]] && TARGET="$(cd -- "${SCRIPT_DIR}/.." && pwd)"
[[ "${MODE}" == "write" ]] && aiaast_assert_non_root_for_repo_writes

defs="${TARGET}/_system/subsystem-definitions.json"
registry="${TARGET}/_system/SYSTEM_REGISTRY.json"
for f in "${defs}" "${registry}"; do
  aiaast_require_file "${f}" || { echo "system_nervous_system_failed missing=${f}"; exit 1; }
done

md_out="${TARGET}/_system/SYSTEM_NERVOUS_SYSTEM.md"
json_out="${TARGET}/_system/system-nervous-system.json"

tmp_md="$(mktemp)"; tmp_json="$(mktemp)"; err="$(mktemp)"
trap 'rm -f "${tmp_md}" "${tmp_json}" "${err}"' EXIT

if ! python3 - "${defs}" "${registry}" "${tmp_md}" "${tmp_json}" "${TARGET}" >"${err}" 2>&1 <<'PY'
import json, sys
from pathlib import Path

defs = json.loads(Path(sys.argv[1]).read_text())
registry = json.loads(Path(sys.argv[2]).read_text())
md_path, json_path, target = sys.argv[3], sys.argv[4], Path(sys.argv[5])

by_path = {e["path"]: e for e in registry.get("entries", [])}

errors, rows = [], []
for s in defs["subsystems"]:
    owner = s["owner_file"]
    validator = s["validator"]
    if owner not in by_path and not (target / owner).exists():
        errors.append(f"{s['id']}: owner_file '{owner}' not in registry and not on disk")
    if not (target / "bootstrap" / validator).exists():
        errors.append(f"{s['id']}: validator '{validator}' not found under bootstrap/")
    oe = by_path.get(owner, {})
    rows.append({
        "id": s["id"],
        "title": s["title"],
        "purpose": s["purpose"],
        "owner_file": owner,
        "authority_level": oe.get("authority_level", "unknown"),
        "validator": validator,
        "downstream_impact": oe.get("downstream_policy", "unknown"),
        "failure_mode": s["failure_mode"],
        "recovery_command": s["recovery_command"],
    })

if errors:
    for e in errors:
        print(e)
    sys.exit(1)

nervous = {"version": defs.get("version", "1.0.0"), "subsystem_count": len(rows), "subsystems": rows}
Path(json_path).write_text(json.dumps(nervous, indent=2, sort_keys=True) + "\n")

lines = []
lines.append("# AIAST System Nervous System")
lines.append("")
lines.append("> GENERATED by `bootstrap/generate-system-nervous-system.sh` from")
lines.append("> `_system/subsystem-definitions.json` + `_system/SYSTEM_REGISTRY.json`.")
lines.append("> Do not edit by hand. This is the one-page \"what matters first\" control")
lines.append("> map; for the full file index see `_system/CAPABILITIES.md` and")
lines.append("> `_system/SYSTEM_REGISTRY.json`. Run any recovery command from the repo root.")
lines.append("")
lines.append(f"**{len(rows)} major subsystems.**")
lines.append("")
lines.append("| Subsystem | Owner file | Authority | Validator | Downstream | Purpose |")
lines.append("|---|---|---|---|---|---|")
for r in rows:
    lines.append(f"| {r['title']} | `{r['owner_file']}` | {r['authority_level']} | `{r['validator']}` | {r['downstream_impact']} | {r['purpose']} |")
lines.append("")
lines.append("## Failure modes & recovery")
lines.append("")
for r in rows:
    lines.append(f"### {r['title']}")
    lines.append(f"- **Failure mode:** {r['failure_mode']}")
    lines.append(f"- **Recovery:** `{r['recovery_command']}`")
    lines.append("")
Path(md_path).write_text("\n".join(lines).rstrip() + "\n")
PY
then
  echo "system_nervous_system_failed"; cat "${err}"; exit 1
fi

if [[ "${MODE}" == "check" ]]; then
  if [[ ! -f "${md_out}" || ! -f "${json_out}" ]]; then
    echo "system_nervous_system_stale: missing generated output"; exit 1
  fi
  if ! diff -q "${tmp_md}" "${md_out}" >/dev/null 2>&1 || ! diff -q "${tmp_json}" "${json_out}" >/dev/null 2>&1; then
    echo "system_nervous_system_stale: regenerate with generate-system-nervous-system.sh --write"
    exit 1
  fi
  echo "system_nervous_system_current path=_system/SYSTEM_NERVOUS_SYSTEM.md"
  exit 0
fi

if [[ "${MODE}" == "write" ]]; then
  cp "${tmp_md}" "${md_out}"; cp "${tmp_json}" "${json_out}"
  echo "Wrote ${md_out}"
  echo "Wrote ${json_out}"
else
  cat "${tmp_md}"
fi
