#!/usr/bin/env bash
# generate-super-template-master-map.sh — Generate super template master map
set -euo pipefail

if [[ $# -lt 1 ]]; then
  echo "usage: $0 <target-repo> [--write] | $0 [--write]"
  exit 2
fi

# Accept either `<target> [--write]` or a leading flag with an implied target
# (the repo root above bootstrap/), matching the other generators so a
# flag-first invocation cannot silently resolve target to "--write" and no-op.
target="$1"
mode="${2:-}"
if [[ "$target" == "--write" || "$target" == "--check" ]]; then
  mode="$target"
  target="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
fi
out="${target}/_system/SUPER_TEMPLATE_MASTER_MAP.md"
tmp="$(mktemp)"

python3 - "$target" >"$tmp" <<'PY'
from __future__ import annotations
import json
import sys
from pathlib import Path

target = Path(sys.argv[1]).resolve()
registry = target / "_system/SYSTEM_REGISTRY.json"
data = {"product": "AIAST", "version": "unknown", "files": []}

if registry.is_file():
    try:
        data = json.loads(registry.read_text(encoding="utf-8"))
    except Exception:
        pass

version = str(data.get("version") or data.get("template_version") or "").strip()
if not version:
    version_file = target / "_system/.template-version"
    if version_file.is_file():
        version = version_file.read_text(encoding="utf-8").strip()
if not version:
    version = "unknown"

managed_entries = []
if isinstance(data.get("entries"), list):
    for item in data["entries"]:
        if isinstance(item, dict) and str(item.get("path", "")).strip():
            managed_entries.append(item)

if managed_entries:
    managed = sorted({str(item.get("path", "")).strip() for item in managed_entries if str(item.get("path", "")).strip()})
else:
    managed = sorted({str(p).strip() for p in data.get("files", []) if str(p).strip()})

entry_by_path = {}
for item in managed_entries:
    path = str(item.get("path", "")).strip()
    if path:
        entry_by_path[path] = item

def gather(rel: str, suffix: str | None = None) -> list[str]:
    root = target / rel
    if not root.is_dir():
        return []
    out = []
    for p in sorted(root.rglob("*")):
        if p.is_file():
            rp = str(p.relative_to(target))
            if suffix and not rp.endswith(suffix):
                continue
            out.append(rp)
    return out

bootstrap = gather("bootstrap", ".sh")
validators = [x for x in bootstrap if "/check-" in f"/{x}" or "/validate-" in f"/{x}"]
archetypes = gather("_system/archetypes", ".md")
tool_memory = gather("_system/tool-memory", ".md")

def pick(substrs: list[str]) -> list[str]:
    return sorted({p for p in managed if any(s in p for s in substrs)})

app_builder = pick(["APP_BUILDER"])
mos = pick(["MOS", "TEMPLATE_MOS"])
fleet = pick(["AGENT_LOCK", "FLEET", "MULTI_AGENT", "agent-state"])
installer = pick(["INSTALL", "UPGRADE", "bootstrap/"])
ports = pick(["/ports/", "PORT_"])
context = pick(["CONTEXT", "/context/"])

generated_markers = [
    "SYSTEM_REGISTRY.json",
    "KEY.md",
    "INTEGRITY_MANIFEST.sha256",
    "REPO_OPERATING_PROFILE.md",
    "repo-operating-profile.json",
    "SUPER_TEMPLATE_MASTER_MAP.md",
]
generated = sorted([p for p in managed if any(m in p for m in generated_markers)])
hand = sorted([p for p in managed if p not in set(generated)])

def mutability_for(path: str) -> str:
    p = path
    if p.startswith("_system/") or p.startswith("bootstrap/") or p in {
        "AGENTS.md", "CODEX.md", "CLAUDE.md", "GEMINI.md", "WINDSURF.md",
        "DEEPSEEK.md", "PEARAI.md", "GROK.md", "LOCAL_MODELS.md", ".cursorrules",
        ".windsurfrules", ".aider.conf.yml", ".continuerules", ".clinerules",
    }:
        return "template-authoritative"
    if p.startswith("ops/") or p.startswith("packaging/") or p.startswith("mobile/") or p.startswith("ai/"):
        return "downstream-mutable-runtime"
    return "downstream-mutable"

print("# AIAST Super Template Master Map")
print("")
print("This file is generated by `bootstrap/generate-super-template-master-map.sh`.")
print("Do not hand-edit generated sections.")
print("")
print("## Generated Snapshot")
print("")
print(f"- Product: {data.get('product', 'AIAST')}")
print(f"- Version: {version}")
print(f"- Managed file count: {len(managed)}")
print(f"- Bootstrap script count: {len(bootstrap)}")
print(f"- Validation script count: {len(validators)}")
print(f"- Archetype pack count: {len(archetypes)}")
print("")
print("## Ownership and Mutability Model")
print("")
print("- Template-managed files are authoritative in source-template mode.")
print("- Downstream mutable surfaces become repo-owned after scaffold/install.")
print("- Runtime app surfaces remain separated from `_system/` governance.")
print("- Generated artifacts should be regenerated via bootstrap scripts.")
print("")
print("## Generated vs Hand-Authored")
print("")
print(f"- Generated managed file count: {len(generated)}")
for p in generated:
    print(f"  - `{p}`")
print(f"- Hand-authored managed file count: {len(hand)}")
print("")

for title, items in [
    ("App-Builder Lane Map", app_builder),
    ("MOS and Meta Lane Map", mos),
    ("Fleet Orchestration Lane Map", fleet),
    ("Installer and Setup Lane Map", installer),
    ("Port and Network Lane Map", ports),
    ("Continuous Context Lane Map", context),
]:
    print(f"## {title}")
    if not items:
        print("- none detected")
    else:
        for p in items:
            print(f"- `{p}`")
    print("")

print("## Scaffold and Archetype Map")
print("")
print("- `_system/SCAFFOLD_PROFILE_MATRIX.md`")
print("- `_system/APP_ARCHETYPE_ROUTING_MATRIX.md`")
for p in archetypes:
    print(f"- `{p}`")
print("")

print("## Tool Adapter and Memory Map")
print("")
print("- `_system/host-adapter-manifest.json`")
for p in tool_memory:
    print(f"- `{p}`")
print("")

print("## Validators by Major Lane")
print("")
for p in validators:
    print(f"- `{p}`")
print("")

print("## Managed File Anchors")
print("")
for p in managed:
    meta = entry_by_path.get(p, {})
    category = str(meta.get("category", "unknown"))
    kind = str(meta.get("kind", "file"))
    size_bytes = meta.get("size_bytes", "unknown")
    gen_flag = "generated" if p in generated else "hand-authored"
    mutability = mutability_for(p)
    print(
        f"- `{p}` (category: `{category}`, kind: `{kind}`, size_bytes: `{size_bytes}`, "
        f"origin: `{gen_flag}`, mutability: `{mutability}`)"
    )
PY

if [[ "$mode" == "--write" ]]; then
  mv "$tmp" "$out"
  echo "wrote: $out"
else
  cat "$tmp"
  rm -f "$tmp"
fi
