#!/usr/bin/env zsh
# Requires zsh; do not invoke as `bash <script>`. Uses zsh-only syntax and
# will syntax-error under bash. Run via `./sync-agent-adapters.sh ...`
# or `zsh sync-agent-adapters.sh ...`.

# AIAST Swarm Fleet: Agent Adapter Synchronization Script
# Generates IDE-specific "thin adapter" rules to synchronize all agents with the SSoT.

set -e

# --- Configuration ---
PROJECT_ROOT=$(git rev-parse --show-toplevel 2>/dev/null || pwd)
SYSTEM_DIR="${PROJECT_ROOT}/TEMPLATE/_system"
MASTER_PROMPT="${SYSTEM_DIR}/MASTER_SYSTEM_PROMPT.md"
SWARM_MANAGER="${PROJECT_ROOT}/TEMPLATE/bootstrap/git-swarm-manager.sh"

# --- Formatting ---
GREEN="\e[32m"
BLUE="\e[34m"
YELLOW="\e[33m"
RESET="\e[0m"

log_info() { echo -e "${GREEN}✅ [SYNC INFO]${RESET} $1" }
log_step() { echo -e "${BLUE}🔹 [SYNC STEP]${RESET} $1" }
log_warn() { echo -e "${YELLOW}⚠️ [SYNC WARN]${RESET} $1" }

# --- Verification ---
[[ ! -d "$SYSTEM_DIR" ]] && { echo "Error: _system directory not found at $SYSTEM_DIR"; exit 1; }
[[ ! -f "$MASTER_PROMPT" ]] && { echo "Error: MASTER_SYSTEM_PROMPT.md not found"; exit 1; }

# --- 1. Cursor Adapter (.cursorrules) ---
log_step "Generating Cursor adapter..."
cat <<EOF > "${PROJECT_ROOT}/.cursorrules"
# Cursor SSoT Adapter
# DO NOT EDIT THIS FILE DIRECTLY. Edit TEMPLATE/_system/ instead.

Load the following repo-local truth in order:
1. AGENTS.md
2. TEMPLATE/_system/INSTRUCTION_PRECEDENCE_CONTRACT.md
3. TEMPLATE/_system/MASTER_SYSTEM_PROMPT.md
4. TEMPLATE/_system/MULTI_AGENT_COORDINATION.md

## Swarm Fleet Rules
- Branch: ai/cursor/<feature>
- Commits: Use '${SWARM_MANAGER} auto-push'
- Anti-Drift: Rule 00-anti-drift-ssot.mdc is active.
EOF

# --- 2. Windsurf Adapter (.windsurfrules) ---
log_step "Generating Windsurf adapter..."
cat <<EOF > "${PROJECT_ROOT}/.windsurfrules"
# Windsurf SSoT Adapter
# DO NOT EDIT THIS FILE DIRECTLY. Edit TEMPLATE/_system/ instead.

{
  "instruction_source": "TEMPLATE/_system/MASTER_SYSTEM_PROMPT.md",
  "swarm_branch_pattern": "ai/windsurf/<feature>",
  "commit_delegation": "${SWARM_MANAGER} auto-push",
  "ssot_policy": "Strict. Mutate TEMPLATE/_system/ only."
}
EOF

# --- 3. Claude/Cline/Roo Adapter (.clinerules) ---
log_step "Generating Claude/Cline adapter..."
cat <<EOF > "${PROJECT_ROOT}/.clinerules"
# Claude/Cline SSoT Adapter
# DO NOT EDIT THIS FILE DIRECTLY. Edit TEMPLATE/_system/ instead.

You are operating within the AIAST Swarm Fleet.
- Source of Truth: TEMPLATE/_system/MASTER_SYSTEM_PROMPT.md
- Branching Policy: ai/claude/<feature>
- Commit Protocol: ${SWARM_MANAGER} auto-push
- Role: Refer to TEMPLATE/_system/agent-performance-profiles.json
EOF

# --- 4. Continue.dev Adapter (.continuerules) ---
log_step "Generating Continue.dev adapter..."
cat <<EOF > "${PROJECT_ROOT}/.continuerules"
# Continue.dev SSoT Adapter
# DO NOT EDIT THIS FILE DIRECTLY. Edit TEMPLATE/_system/ instead.

Follow the instructions in TEMPLATE/_system/MASTER_SYSTEM_PROMPT.md.
Commits must be handled by ${SWARM_MANAGER}.
EOF

# --- 5. Copilot Instructions (.github/copilot-instructions.md) ---
# (Already managed by write_file in previous turn, but we ensure it exists)
if [[ ! -f "${PROJECT_ROOT}/TEMPLATE/.github/copilot-instructions.md" ]]; then
    log_warn "Copilot instructions missing. Generating baseline..."
    mkdir -p "${PROJECT_ROOT}/TEMPLATE/.github"
    touch "${PROJECT_ROOT}/TEMPLATE/.github/copilot-instructions.md"
fi

# --- 6. Repository-Level symlinks (for IDEs that only look at root) ---
log_step "Updating root-level symlinks to TEMPLATE/.github..."
mkdir -p "${PROJECT_ROOT}/.github"
ln -sf "../TEMPLATE/.github/copilot-instructions.md" "${PROJECT_ROOT}/.github/copilot-instructions.md"

# --- 7. Gitignore update ---
log_step "Updating .gitignore for agent ephemeral files..."
grep -q ".cursor/rules/.state" "${PROJECT_ROOT}/.gitignore" || echo "\n# Agent Ephemeral Files\n.cursor/rules/.state\n.windsurf_cache/\n.claude_cache/" >> "${PROJECT_ROOT}/.gitignore"

log_info "AIAST Swarm Fleet synchronization complete. All agents are now SSoT-aligned."
