#requires -Version 5.1
<#
.SYNOPSIS
  Scaffold installer for __AIAST_APP_NAME__ (Windows).

.DESCRIPTION
  - Checks elevation for system-wide paths.
  - Creates install and config directories.
  - Picks an available loopback TCP port in a safe range unless -Port is set.
  - Writes a machine-local env file (no secrets).

  Replace or wrap this script with MSIX/winget for production signing and updates.

.PARAMETER InstallScope
  User | Machine

.PARAMETER Port
  Force a specific listen port (must be free).

.PARAMETER DryRun
  Print actions only.

.EXAMPLE
  .\Install.ps1 -InstallScope User
#>
[CmdletBinding()]
param(
    [ValidateSet('User', 'Machine')]
    [string]$InstallScope = 'User',

    [int]$Port = 0,

    [switch]$DryRun
)

$ErrorActionPreference = 'Stop'
$AppName = '__AIAST_APP_NAME__'
$AppSlug = '__AIAST_APP_SLUG__'

function Write-Log([string]$Message) {
    $ts = (Get-Date).ToString('o')
    Write-Host "[$ts] $Message"
}

function Test-IsAdmin {
    $id = [Security.Principal.WindowsIdentity]::GetCurrent()
    $p = New-Object Security.Principal.WindowsPrincipal($id)
    return $p.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
}

function Get-DefaultPort {
    $rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
    $bytes = New-Object byte[] 2
    $rng.GetBytes($bytes)
    $offset = [BitConverter]::ToUInt16($bytes, 0) % 100
    return 46300 + $offset
}

function Test-PortFree([int]$TcpPort) {
    $listener = $null
    try {
        $listener = New-Object System.Net.Sockets.TcpListener([System.Net.IPAddress]::Loopback, $TcpPort)
        $listener.Start()
        return $true
    }
    catch {
        return $false
    }
    finally {
        if ($null -ne $listener) {
            try { $listener.Stop() } catch { }
        }
    }
}

try {
    Start-Transcript -Path "$env:TEMP\${AppSlug}-install.log" -Append | Out-Null
}
catch {
    Write-Log "Transcript unavailable: $($_.Exception.Message)"
}

try {
    if ($InstallScope -eq 'Machine' -and -not (Test-IsAdmin)) {
        throw "Machine scope requires Administrator PowerShell. Re-run elevated or use -InstallScope User."
    }

    if ($InstallScope -eq 'Machine') {
        $Root = Join-Path $env:ProgramFiles $AppName
        $Cfg = Join-Path $env:ProgramData $AppSlug
    }
    else {
        $Root = Join-Path $env:LOCALAPPDATA "Programs\$AppName"
        $Cfg = Join-Path $env:LOCALAPPDATA $AppSlug
    }

    $chosen = if ($Port -gt 0) { $Port } else { Get-DefaultPort }
    if ($Port -le 0) {
        for ($i = 0; $i -lt 80; $i++) {
            if (Test-PortFree -TcpPort $chosen) { break }
            $chosen = Get-DefaultPort
        }
        if (-not (Test-PortFree -TcpPort $chosen)) {
            throw "Could not find a free TCP port after retries; specify -Port explicitly."
        }
    }
    elseif (-not (Test-PortFree -TcpPort $chosen)) {
        throw "Port $chosen is not free."
    }

    Write-Log "InstallScope=$InstallScope Root=$Root Cfg=$Cfg Port=$chosen DryRun=$DryRun"

    if ($DryRun) {
        Write-Log 'Dry run complete.'
        exit 0
    }

    New-Item -ItemType Directory -Force -Path $Root, $Cfg | Out-Null

    $envFile = Join-Path $Cfg 'install.env'
    @(
        "# Generated by Install.ps1 — add secrets via secure store, not this file.",
        "APP_NAME=$AppName",
        "APP_BIND_ADDRESS=127.0.0.1",
        "APP_PORT=$chosen"
    ) | Set-Content -Path $envFile -Encoding UTF8

    Write-Log "Wrote $envFile"
    Write-Log 'Scaffold install finished. Integrate your binaries and services next.'
    exit 0
}
catch {
    Write-Error $_
    exit 1
}
finally {
    try { Stop-Transcript | Out-Null } catch { }
}
